# -*- coding: utf-8 -*-
"""lab2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kS94SPg1r-DjbKmMB5Z5qLO3R0x_vHXE
"""

#include <iostream>
#include <vector>
#include <cmath>
#include <fstream>

using namespace std;

double get_evkl_norm(const vector<double>& x) {
    double sum = 0;
    for (auto a : x) {
        sum += a * a;
    }
    return sqrt(sum);
}

vector<double> matr_vec_mult(vector<vector<double>> matr, vector<double> vec) {
    vector<double> res;
    for (int i = 0; i < matr.size(); i++){
        double sum = 0;
        for (int j = 0; j < matr.size(); j++){
            sum += matr[i][j] * vec[j];
        }
        res.push_back(sum);
    }
    return res;
}

vector<double> Gauss(vector<vector<double>> x, const vector<double>& vec) {
    int i = 0;
    double tmp;
    int m = x.size();

    for (auto v : vec) {
        x[i].push_back(v);
        i++;
    }

    vector<double> res;
    for (int i = 0; i < m; i++) {
        res.push_back(0);
    }

    for (i = 0; i < m; i++) {
        tmp = x[i][i];
        for (int j = m; j >= i; j--) {
            x[i][j] /= tmp;
        }
        for (int j = i + 1; j < m; j++) {
            tmp = x[j][i];
            for (int k = m; k >= i; k--)
                x[j][k] -= tmp * x[i][k];
        }
    }

    res[m - 1] = x[m - 1][m];
    for (int i = m - 2; i >= 0; i--) {
        res[i] = x[i][m];
        for (int j = i + 1; j < m; j++) {
            res[i] -= x[i][j] * res[j];
        }
    }
    return res;
}

vector<vector<double>> generate_matrix(int n, double a, double b, double por) {
    vector<vector<double>> matr;
    for (int i = 0; i < n; i++) {
        vector<double> arr;
        for (int j = 0; j < n; j++) {
            double r = a + (double)rand() / RAND_MAX * (b - a);
            if (i == j) {
                r = pow(r, por);
            }
            arr.push_back(r);
        }
        matr.push_back(arr);
    }
    return matr;
}

void input(const string& path, vector<vector<double>>& matr, vector<double>& vec) {
    ifstream fin(path);
    if (!fin.is_open()) {
        cout << "Error openning file\n";
        return;
    }
    string s;
    getline(fin, s);
    if (s == "input") {
        while (!s.empty()) {
            getline(fin, s);
            vector<double> x;
            string substr;
            for (int i = 0; i < s.size(); i++) {
                char c = s[i];
                if (c == ' ') {
                    x.push_back(stod(substr));
                    substr = "";
                } else {
                    substr += c;
                    if (i == s.size() - 1) {
                        x.push_back(stod(substr));
                    }
                }
            }
            if (!x.empty()) {
                matr.push_back(x);
            }
            x.clear();
        }
        getline(fin, s);
        string substr;
        for (int i = 0; i < s.size(); i++) {
            char c = s[i];
            if (c == ' ') {
                vec.push_back(stod(substr));
                substr = "";
            } else {
                substr += c;
                if (i == s.size() - 1) {
                    vec.push_back(stod(substr));
                }
            }
        }
    } else {
        getline(fin, s);
        int n = stoi(s);
        double a, b;
        fin >> a >> b;
        double por;
        fin >> por;
        matr = generate_matrix(n, a, b, por);
    }
    fin.close();
}

void print(const vector<vector<double>>& matr) {
    cout << '[';
    for (const auto& i : matr) {
        cout << '[';
        for (auto x : i) {
            cout << fixed << x << ", ";
        }
        cout << "],";
        cout << endl;
    }
    cout << ']' << endl;
}

void print(const vector<double>& vec) {
    cout << '[';
    for (auto x : vec) {
        cout << fixed << x << ", ";
    }
    cout << ']';
    cout << endl;
}

double check_vectors(vector<double> res, vector<double> v) {
    vector<double> diff;
    for (int i = 0; i < res.size(); i++) {
        diff.push_back(res[i] - v[i]);
    }
    return get_evkl_norm(diff);
}

int main() {
    vector<vector<double>> matr;
    vector<double> vec;
    for (int i = 2; i < 3; i++) {
        input("../tests/test" + to_string(i) + ".txt", matr, vec);
        cout << "TEST " << i << endl;
        vector<double> v;
        for (int i = 0; i < 5; i++) {
            v.push_back(-5 + (double)rand() / RAND_MAX * (5 + 5));
        }
        vec = matr_vec_mult(matr, v);
        auto res = Gauss(matr, vec);
        cout.precision(20);
        print(matr);
        cout << "--------\n";
        print(vec);
        cout << "--------\n";


        print(res);
        print(v);
        cout << check_vectors(res, v);


        cout << endl << "---------------" << endl;
    }
    return 0;
}

def evkl_norm(vec):
  sum = 0
  for x in vec:
    sum += x ** 2
  return numpy.sqrt(sum)

import numpy

matr = [[73.30252631345379654704, 4.54944634137183712141, 8.04789301382745314584, 8.18596030128465912412, 9.20482622143105899681, ],
[2.77796232364045536656, 16.13632757474381662632, 7.91406635330713648102, 3.49997239722869002421, 5.98572960215887484026, ],
[5.29657346675944218362, 6.65983832285732013645, 18.34460514904505146205, 5.62060819176053971802, 9.57006752657241577253, ],
[9.24575561203330664739, 6.72140555163910846659, 7.45567236489414764122, 5.17299997475122363966, 6.46271988631352733989, ],
[1.14670514461896622116, 3.18598093566763251872, 2.23508419107416855809, 8.23759078804291355880, 5.80863890434216401104, ],
]





vec = [-106.02759481929433604819, -92.85124401132509319723, -100.58480336160495483000, -55.60656055044512413588, 3.05978698836912244019, ]

abs_v = [-0.99055605753816511339, -3.70209553218544273889, -3.91191197974230719936, 4.98924518003559036572, -2.81743094689093132033, ]


def lib_ans(matr, vec):
  return numpy.linalg.solve(matr, vec)

print(lib_ans(matr, vec))
print(evkl_norm(abs_v - lib_ans(matr, vec)))